version: "3"

services:
  zookeeper-1:
    image: zookeeper:3.4.9
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-zookeeper-1
    restart: on-failure
    environment:
      ZOO_MY_ID: 1 # The id for the zookeeper in the cluster
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper-2:2889:3889 server.3=zookeeper-3:2890:3890 # A list of all the zookeeper nodes in the cluster
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181 # Zookeeper listner
      - 3888:3888 # Quorum listening port
      - 2888:2888 # Quorum listening port

  zookeeper-2:
    image: zookeeper:3.4.9
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-zookeeper-2
    restart: on-failure
    environment:
      ZOO_MY_ID: 2 # The id for the zookeeper in the cluster
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=0.0.0.0:2889:3889 server.3=zookeeper-3:2890:3890 # A list of all the zookeeper nodes in the cluster
      ZOOKEEPER_CLIENT_PORT: 2182
    ports:
      - 2182:2182 # Zookeeper listner
      - 3889:3889 # Quorum listening port
      - 2889:2889 # Quorum listening port

  zookeeper-3:
    image: zookeeper:3.4.9
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-zookeeper-3
    restart: on-failure
    environment:
      ZOO_MY_ID: 3 # The id for the zookeeper in the cluster
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2889:3889 server.3=0.0.0.0:2890:3890 # A list of all the zookeeper nodes in the cluster
      ZOOKEEPER_CLIENT_PORT: 2183
    ports:
      - 2183:2183 # Zookeeper listner
      - 3890:3890 # Quorum listening port
      - 2890:2890 # Quorum listening port

  kafka-broker-1:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-broker-1
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      KAFKA_BROKER_ID: 0
      KAFKA_HEAP_OPTS: -Xms512M -Xmx1G
    ports:
      - 9092:9092 # Broker listner

  kafka-broker-2:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-broker-2
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: -Xms512M -Xmx1G
    ports:
      - 9093:9093 # Broker listner

  kafka-broker-3:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-broker-3
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      KAFKA_BROKER_ID: 2
      KAFKA_HEAP_OPTS: -Xms512M -Xmx1G
    ports:
      - 9094:9094 # Broker listner

