version: "3"

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-zookeeper-1
    restart: on-failure
    environment:
      ZOO_MY_ID: 1 # The id for the zookeeper in the cluster
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2889:3889 server.3=zoo3:2890:3890 # A list of all the zookeeper nodes in the cluster
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181" # Zookeeper listner
      - "3888:3888" # Quorum listening port
      - "2888:2888" # Quorum listening port

  zoo2:
    image: zookeeper:3.4.9
    hostname: zoo2
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-zookeeper-2
    restart: on-failure
    environment:
      ZOO_MY_ID: 2 # The id for the zookeeper in the cluster
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2889:3889 server.3=zoo3:2890:3890 # A list of all the zookeeper nodes in the cluster
      ZOOKEEPER_CLIENT_PORT: 2182
    ports:
      - "2182:2182" # Zookeeper listner
      - "3889:3889" # Quorum listening port
      - "2889:2889" # Quorum listening port

  zoo3:
    image: zookeeper:3.4.9
    hostname: zoo3
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-zookeeper-3
    restart: on-failure
    environment:
      ZOO_MY_ID: 3 # The id for the zookeeper in the cluster
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2889:3889 server.3=zoo3:2890:3890 # A list of all the zookeeper nodes in the cluster
      ZOOKEEPER_CLIENT_PORT: 2183
    ports:
      - "2183:2183" # Zookeeper listner
      - "3890:3890" # Quorum listening port
      - "2890:2890" # Quorum listening port

  broker1:
    image: confluentinc/cp-kafka:5.3.1
    hostname: broker1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-broker-1
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 0
      KAFKA_HEAP_OPTS: -Xms512M -Xmx1G
    ports:
      - "9092:9092" # Broker listner

  broker2:
    image: confluentinc/cp-kafka:5.3.1
    hostname: broker2
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-broker-2
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: -Xms512M -Xmx1G
    ports:
      - "9093:9093" # Broker listner

  broker3:
    image: confluentinc/cp-kafka:5.3.1
    hostname: broker3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    deploy:
      placement:
        constraints:
          - node.hostname==kafka-broker-3
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 2
      KAFKA_HEAP_OPTS: -Xms512M -Xmx1G
    ports:
      - "9094:9094" # Broker listner

